### ISSUE TITLE
Error on 'if() return' with no semicolon

### ISSUE THREAD

**Issue by Rob-ot** [js2coffee/js2coffee#160]
The following code blows up:

```
function z (a) {
  if (a) return
  var b = g()
}
```

with:
```
SyntaxError: missing operand
    at Object.newSyntaxError (/usr/lib/node_modules/js2coffee/lib/narcissus_packed.js:825:21)
    at PrimaryExpression (/usr/lib/node_modules/js2coffee/lib/narcissus_packed.js:2227:21)
    at MemberExpression (/usr/lib/node_modules/js2coffee/lib/narcissus_packed.js:2071:17)
    at UnaryExpression (/usr/lib/node_modules/js2coffee/lib/narcissus_packed.js:2043:17)
    at MultiplyExpression (/usr/lib/node_modules/js2coffee/lib/narcissus_packed.js:2008:13)
    at AddExpression (/usr/lib/node_modules/js2coffee/lib/narcissus_packed.js:1994:13)
    at ShiftExpression (/usr/lib/node_modules/js2coffee/lib/narcissus_packed.js:1980:13)
    at RelationalExpression (/usr/lib/node_modules/js2coffee/lib/narcissus_packed.js:1964:13)
    at EqualityExpression (/usr/lib/node_modules/js2coffee/lib/narcissus_packed.js:1944:13)
    at BitwiseAndExpression (/usr/lib/node_modules/js2coffee/lib/narcissus_packed.js:1930:13)
```

js2coffee version 0.2.0

**Comment by rstacruz** [comment]
took a while, all fixed :) [demo](http://js2.coffee/#try:function%20z%28%29%20{%0A%20%20%20%20if%20%28a%29%20return%0A%20%20%20%20this.set%28%22abc%22%29%0A})

**Comment by Rob-ot** [comment]
@rstacruz Horrah, that's amazing! Thanks for fixing this!
