### ISSUE TITLE
Unknown node type RestElement. 

### ISSUE THREAD

**Issue by zaoqi** [js2coffee/js2coffee#506]
```
Unknown node type RestElement.
Error: Unknown node type RestElement.
    at E.j [as replace] (/home/1828_sandbox/src/the-language/core/arch/coffeescript/node_modules/js2coffee/dist/js2coffee.js:7:30844)
    at Object.B [as replace] (/home/1828_sandbox/src/the-language/core/arch/coffeescript/node_modules/js2coffee/dist/js2coffee.js:7:312
85)
    at t.recurse (/home/1828_sandbox/src/the-language/core/arch/coffeescript/node_modules/js2coffee/dist/js2coffee.js:1:21000)
    at t.run (/home/1828_sandbox/src/the-language/core/arch/coffeescript/node_modules/js2coffee/dist/js2coffee.js:1:20621)
    at Function.t.run (/home/1828_sandbox/src/the-language/core/arch/coffeescript/node_modules/js2coffee/dist/js2coffee.js:1:20397)

    at o (/home/1828_sandbox/src/the-language/core/arch/coffeescript/node_modules/js2coffee/dist/js2coffee.js:1:1460)
    at Function.s.transform (/home/1828_sandbox/src/the-language/core/arch/coffeescript/node_modules/js2coffee/dist/js2coffee.js:1:1504
)
    at Function.s.build (/home/1828_sandbox/src/the-language/core/arch/coffeescript/node_modules/js2coffee/dist/js2coffee.js:1:1107)
    at /home/1828_sandbox/src/the-language/core/arch/coffeescript/node_modules/js2coffee/bin/js2coffee:29:27
    at Array.forEach (<anonymous>)
```

**Comment by zaoqi** [comment]
https://gitlab.com/the-language/the-language/blob/8574e2e863a0f316462064c63295889e61e3a716/core/arch/ecmascript6/lang.js
```
1828_sandbox@dzeaboiqain:~/src/the-language/core/arch/coffeescript$ cat ../ecmascript6/lang.js | sed 's|^export .*$||' | npx js2coffee
> lang.coffee
Unknown node type RestElement.
Error: Unknown node type RestElement.
    at E.j [as replace] (/home/1828_sandbox/src/the-language/core/arch/coffeescript/node_modules/js2coffee/dist/js2coffee.js:7:30844)
    at Object.B [as replace] (/home/1828_sandbox/src/the-language/core/arch/coffeescript/node_modules/js2coffee/dist/js2coffee.js:7:312
85)
    at t.recurse (/home/1828_sandbox/src/the-language/core/arch/coffeescript/node_modules/js2coffee/dist/js2coffee.js:1:21000)
    at t.run (/home/1828_sandbox/src/the-language/core/arch/coffeescript/node_modules/js2coffee/dist/js2coffee.js:1:20621)
    at Function.t.run (/home/1828_sandbox/src/the-language/core/arch/coffeescript/node_modules/js2coffee/dist/js2coffee.js:1:20397)

    at o (/home/1828_sandbox/src/the-language/core/arch/coffeescript/node_modules/js2coffee/dist/js2coffee.js:1:1460)
    at Function.s.transform (/home/1828_sandbox/src/the-language/core/arch/coffeescript/node_modules/js2coffee/dist/js2coffee.js:1:1504
)
    at Function.s.build (/home/1828_sandbox/src/the-language/core/arch/coffeescript/node_modules/js2coffee/dist/js2coffee.js:1:1107)
    at /home/1828_sandbox/src/the-language/core/arch/coffeescript/node_modules/js2coffee/bin/js2coffee:29:27
    at Array.forEach (<anonymous>)
```
